version: "3"
services:
  cloudsaver:
    image: jiangrui1994/cloudsaver:latest
    container_name: cloud-saver2
    ports:
      - "5000:8008"
    volumes:
      - ./app/data:/app/data
      - ./app/config:/app/config
    restart: unless-stopped